name: Dev Deploy
on:
  push:
    branches: [develop]

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  ECR_REPO: 123456789012.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/go-vue-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, push
        run: |
          docker build -t go-vue-app .
          docker tag go-vue-app:latest $ECR_REPO:latest
          docker push $ECR_REPO:latest

      - name: Deploy infra
        run: |
          cd infra
          terraform init
          terraform apply -auto-approve -var="image_tag=latest"